spring:
  application:
    name: DevJobs

  datasource:
    url: jdbc:mysql://${bddurl}:${bddport}/${bdd}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${bdduser}
    password: ${bddpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

jwtsecret: ${JWT_SECRET}
jwtexpiration: ${JWT_EXPIRATION}

server:
  port: 8080